image: docker:stable

variables:
  # When using dind service we need to instruct docker, to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  #
  # Note that if you're using Kubernetes executor, the variable should be set to
  # tcp://localhost:2375 because of how Kubernetes executor connects services
  # to the job container
  DOCKER_HOST: tcp://docker:2375/
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: devicemapper

services:
  - docker:dind

before_script:
  - docker login -u jenkinsci -p $CI_JOB_TOKEN portus.egame.vn
  -  docker info

build-dev:
  stage: build
  script:
    - docker build -t portus.egame.vn/ci/dhcd:dev .
    - docker push portus.egame.vn/ci/dhcd:dev
  only:
    - dev

## should have unitest stage before build and push master image
build-master:
  stage: build
  script:
    - docker build -t portus.egame.vn/ci/dhcd:master .
    - docker push portus.egame.vn/ci/dhcd:master
  only:
    - master
